#!/bin/sh
echo Content-type: text/html
echo ""
./make_chart --no-content-header -d 1 --file voorbeeld-parsedfileformat/test1 --parse-profile profile1
./make_chart --no-content-header -d 2 --file voorbeeld-parsedfileformat/test1 --parse-profile profile1