#!/bin/sh
echo Content-type: text/html
echo ""
listid[0]=1
listid[1]=2
LOADSCRIPT_PT1=script1.js
/bin/cat <<EOF
<html>
<head>
<link rel="stylesheet" type="text/css" href="stijl/stijl.css" />
<title>Data visualisatie</title>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
EOF
cat $LOADSCRIPT_PT1
./make_chart --no-content-header -d ${listid[0]} --file voorbeeld-parsedfileformat/test1 --parse-profile profile1 --title "IP-data usage"
./make_chart --no-content-header -d ${listid[1]} --file voorbeeld-parsedfileformat/test1 --parse-profile profile1 --title "Broadcast-traffic"
/bin/cat <<EOF 
}</script>
</head>
<body>
  <div class="out">
    <div class="inner-left">
      <div id="chart_div_1">
        </div>
    </div>
    <div class="inner-right">
      <div id="chart_div_2">
        </div>
    </div>
</div>
</body>
</html>
EOF