#!/bin/sh
function addcolomn(){
    if [ -x $1 ]; then
	echo -e "['DATA_POINT', VALUE],"
    else
	echo -e "['DATA_POINT', VALUE]"
    fi
}

contentheaderflag=yes
divid=0
filename=NULL
parseprofile=profile1 #de suite van sed scripts die moeten worden gebruikt om dit soort data te parsen.

DATAFILE=voorbeeld-parsedfileformat/test1  #de dataset waaruit we de data moeten halen om te werken
DATAFILE_RECORDS=$(cat $DATAFILE |wc -l) # aantal records in de datafile
PROFILEPATH="sed-scripts/"
counter=0 #de counter om in de loop bij te houden hoeveel er al is geloopt
longopts="no-content-header,div-id,file:,parse-profile:,title:"
shortopt="nd:f:p:t:"
ARGUMENTS=$(getopt -s bash --options $shortopt --longoptions $longopts -- "$@")
eval set -- $ARGUMENTS
while true ; do
    case $1 in
	-n|--no-content-header) contentheaderflag=no; shift;;
	-p|--parse-profile)  shift; parseprofile="$1"; shift;;
	-d|--div-id) shift; divid="$1"; shift;;
	-f|--file) shift; filename="$1"; shift;;
	-t|--title) shift; title="$1"; shift;;
	--) shift; break;;
	*) shift; break;;
    esac
done
PROFILEPATH=$PROFILEPATH$parseprofile

if [ $contentheaderflag == "yes" ]; then
    echo Content-type: text/html
    echo ""
fi

breedte=600
hoogte=500
LOADSCRIPT_PT2=script2.js
LOADSCRIPT_PT3=script3.js
cat $LOADSCRIPT_PT2
for i in $(cat $DATAFILE); do
   counter=$((counter+1))
   ipadr=$(echo $i |sed -f  $PROFILEPATH"-parseip.sed")
   value=$( echo $i |sed -f $PROFILEPATH"-parseconnection.sed")
   if [ $counter -ne $DATAFILE_RECORDS ]; then
       addcolomn   |sed -e "s/DATA_POINT/$ipadr/;s/VALUE/$value/"
   else
       addcolomn A |sed -e "s/DATA_POINT/$ipadr/;s/VALUE/$value/" 
   fi
done

cat $LOADSCRIPT_PT3 |sed -e "s/title_replace/$title/;\
s/breedte_replace/$breedte/;\
s/hoogte_replace/$hoogte/;\
s/ID_NUMBER/$divid/g"
